// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: protobuf/booking.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookingInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start   int64  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End     int64  `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Shop_ID int64  `protobuf:"varint,3,opt,name=shop_ID,json=shopID,proto3" json:"shop_ID,omitempty"`
	Biz     string `protobuf:"bytes,4,opt,name=biz,proto3" json:"biz,omitempty"`
}

func (x *BookingInfo) Reset() {
	*x = BookingInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_booking_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingInfo) ProtoMessage() {}

func (x *BookingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_booking_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingInfo.ProtoReflect.Descriptor instead.
func (*BookingInfo) Descriptor() ([]byte, []int) {
	return file_protobuf_booking_proto_rawDescGZIP(), []int{0}
}

func (x *BookingInfo) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *BookingInfo) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *BookingInfo) GetShop_ID() int64 {
	if x != nil {
		return x.Shop_ID
	}
	return 0
}

func (x *BookingInfo) GetBiz() string {
	if x != nil {
		return x.Biz
	}
	return ""
}

type BookingInfos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*BookingInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *BookingInfos) Reset() {
	*x = BookingInfos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_booking_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingInfos) ProtoMessage() {}

func (x *BookingInfos) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_booking_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingInfos.ProtoReflect.Descriptor instead.
func (*BookingInfos) Descriptor() ([]byte, []int) {
	return file_protobuf_booking_proto_rawDescGZIP(), []int{1}
}

func (x *BookingInfos) GetItems() []*BookingInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_protobuf_booking_proto protoreflect.FileDescriptor

var file_protobuf_booking_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x22, 0x60, 0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x68, 0x6f,
	0x70, 0x5f, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x68, 0x6f, 0x70,
	0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x7a, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x62, 0x69, 0x7a, 0x22, 0x3b, 0x0a, 0x0c, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x49,
	0x6e, 0x66, 0x6f, 0x73, 0x12, 0x2b, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_booking_proto_rawDescOnce sync.Once
	file_protobuf_booking_proto_rawDescData = file_protobuf_booking_proto_rawDesc
)

func file_protobuf_booking_proto_rawDescGZIP() []byte {
	file_protobuf_booking_proto_rawDescOnce.Do(func() {
		file_protobuf_booking_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_booking_proto_rawDescData)
	})
	return file_protobuf_booking_proto_rawDescData
}

var file_protobuf_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_booking_proto_goTypes = []interface{}{
	(*BookingInfo)(nil),  // 0: protobuf.BookingInfo
	(*BookingInfos)(nil), // 1: protobuf.BookingInfos
}
var file_protobuf_booking_proto_depIdxs = []int32{
	0, // 0: protobuf.BookingInfos.items:type_name -> protobuf.BookingInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_booking_proto_init() }
func file_protobuf_booking_proto_init() {
	if File_protobuf_booking_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_booking_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookingInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_booking_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookingInfos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_booking_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_booking_proto_goTypes,
		DependencyIndexes: file_protobuf_booking_proto_depIdxs,
		MessageInfos:      file_protobuf_booking_proto_msgTypes,
	}.Build()
	File_protobuf_booking_proto = out.File
	file_protobuf_booking_proto_rawDesc = nil
	file_protobuf_booking_proto_goTypes = nil
	file_protobuf_booking_proto_depIdxs = nil
}
